# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/russian95/Xylon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/russian95/Xylon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/russian95/Xylon/CMakeFiles /home/russian95/Xylon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/russian95/Xylon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XylonEngine

# Build rule for target.
XylonEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XylonEngine
.PHONY : XylonEngine

# fast build rule for target.
XylonEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/build
.PHONY : XylonEngine/fast

#=============================================================================
# Target rules for targets named clean_project

# Build rule for target.
clean_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_project
.PHONY : clean_project

# fast build rule for target.
clean_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_project.dir/build.make CMakeFiles/clean_project.dir/build
.PHONY : clean_project/fast

Unity/unity_0_cxx.o: Unity/unity_0_cxx.cxx.o
.PHONY : Unity/unity_0_cxx.o

# target to build an object file
Unity/unity_0_cxx.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_0_cxx.cxx.o
.PHONY : Unity/unity_0_cxx.cxx.o

Unity/unity_0_cxx.i: Unity/unity_0_cxx.cxx.i
.PHONY : Unity/unity_0_cxx.i

# target to preprocess a source file
Unity/unity_0_cxx.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_0_cxx.cxx.i
.PHONY : Unity/unity_0_cxx.cxx.i

Unity/unity_0_cxx.s: Unity/unity_0_cxx.cxx.s
.PHONY : Unity/unity_0_cxx.s

# target to generate assembly for a file
Unity/unity_0_cxx.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_0_cxx.cxx.s
.PHONY : Unity/unity_0_cxx.cxx.s

Unity/unity_1_cxx.o: Unity/unity_1_cxx.cxx.o
.PHONY : Unity/unity_1_cxx.o

# target to build an object file
Unity/unity_1_cxx.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_1_cxx.cxx.o
.PHONY : Unity/unity_1_cxx.cxx.o

Unity/unity_1_cxx.i: Unity/unity_1_cxx.cxx.i
.PHONY : Unity/unity_1_cxx.i

# target to preprocess a source file
Unity/unity_1_cxx.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_1_cxx.cxx.i
.PHONY : Unity/unity_1_cxx.cxx.i

Unity/unity_1_cxx.s: Unity/unity_1_cxx.cxx.s
.PHONY : Unity/unity_1_cxx.s

# target to generate assembly for a file
Unity/unity_1_cxx.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XylonEngine.dir/build.make CMakeFiles/XylonEngine.dir/Unity/unity_1_cxx.cxx.s
.PHONY : Unity/unity_1_cxx.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean_project"
	@echo "... XylonEngine"
	@echo "... Unity/unity_0_cxx.o"
	@echo "... Unity/unity_0_cxx.i"
	@echo "... Unity/unity_0_cxx.s"
	@echo "... Unity/unity_1_cxx.o"
	@echo "... Unity/unity_1_cxx.i"
	@echo "... Unity/unity_1_cxx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

